# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "2.6"

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source south_central runtests.py

# report coverage to coveralls.io
after_success: coveralls